const INITIALIZE_STORE = "INIT_STORE";
const UPDATE_STORE = "UPDATE_STORE";
const INITIALIZE_MAP = "INITIALIZE_MAP";
const TOGGLE_GROUP = "TOGGLE_GROUP";
const TOGGLE_ITEM = "TOGGLE_ITEM";
const SELECT_ITEM = "SELECT_ITEM";
const CHANGE_OPACITY = "CHANGE_OPACITY";
const CROP = "CROP";
const ZOOM_TO_LAYER = "ZOOM_TO_LAYER";
const UPDATE_MASK = "UPDATE_MASK";
const ADD_RESOURCE = "ADD_RESOURCE";
const REMOVE_RESOURCE = "REMOVE_RESOURCE";
const CHANGE_PROJECT = "CHANGE_PROJECT";

module.exports = {
  INITIALIZE_STORE,
  UPDATE_STORE,
  INITIALIZE_MAP,
  TOGGLE_GROUP,
  TOGGLE_ITEM,
  SELECT_ITEM,
  CHANGE_OPACITY,
  CROP,
  ZOOM_TO_LAYER,
  UPDATE_MASK,
  ADD_RESOURCE,
  REMOVE_RESOURCE,
  CHANGE_PROJECT,
};
